// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojsyhxjgohketmducebf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qc3loeGpnb2hrZXRtZHVjZWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjcwMjcsImV4cCI6MjA2NTA0MzAyN30.btPBncfNDA6ltagGDoDpG93uKvl8J7_hYXrfuCVibW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);